version: "3.3"

services:
  broker1:
    build:
      context: ../docker-build/activemq/   
    deploy:
      resources:
        limits:
          memory: 512M
    ports:
      - "8161:8161"
    expose:
      - "61616"
      - "9876"
    networks:
      artemis_network:
        ipv4_address: 172.20.0.100
      
 
  selector1:
    depends_on:
      - broker1
    build:
      context: ../docker-build/selector1/
    networks:
      artemis_network:
        ipv4_address: 172.20.0.103
  
  selector2:
    depends_on:
      - broker1
    build:
      context: ../docker-build/selector2/
    networks:
      artemis_network:
        ipv4_address: 172.20.0.104

  sender:
    depends_on:
      - broker1
    build:
      context: ../docker-build/sender/
    networks:
      artemis_network:
        ipv4_address: 172.20.0.105
  

networks:
  artemis_network:
    ipam:
      config:
        - subnet: 172.20.0.0/16