<?xml version="1.0" encoding="utf-8"?>
<ns:IntegrateAnnouncement xmlns:ns="http://services.ssw.soget.fr/201511/"
    xmlns:edi="http://schemas.ssw.soget.fr/edi/"
    xmlns:ns1="http://schemas.ssw.soget.fr/201308/"
    xmlns:ann="http://schemas.ssw.soget.fr/201511/announcement"
    xmlns:ns2="http://schemas.ssw.soget.fr/201504/">
    <ns:header>
        <edi:Application>S-ONE_PSW</edi:Application>
        <edi:Owner>EDIGREG</edi:Owner>
        <edi:MessageType>http://services.ssw.soget.fr/201511/#IntegrateAnnouncement</edi:MessageType>
        <edi:InterchangeId>2006232323230000</edi:InterchangeId>
        <edi:Date>2017-02-27T08:45:45Z</edi:Date>
        <edi:InterfaceCode>INTDOC</edi:InterfaceCode>
    </ns:header>
    <ns:announcement>
        <ns1:Sender>CGREG</ns1:Sender>
	<!--/ns:announcement-->
</ns:IntegrateAnnouncement>